---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alert-rules
  namespace: monitoring
  labels:
    grafana_alert_rules: "1"
data:
  alerts.yaml: |
    apiVersion: 1
    groups:
      - orgId: 1
        name: Cluster-Disaster-Rules
        folder: Infrastructure Alerts
        interval: 10s
        rules:
          - uid: pod_crash_alert
            title: Kubernetes Container Down Disaster
            condition: C
            data:
              - refId: A
                relativeTimeRange:
                  from: 60
                  to: 0
                datasourceUid: 'prometheus'
                model:
                  expr: kube_deployment_status_replicas_available{deployment="dr-web-app"} == 0
                  intervalMs: 10000
                  maxDataPoints: 43200
                  refId: A
              - refId: C
                model:
                  expression: A
                  type: threshold
                  refId: C
                  conditions:
                    - evaluator:
                        params: [0]
                        type: "eq"
                      operator:
                        type: "and"
                      query:
                        params: ["A"]
                      reducer:
                        params: []
                        type: "last"
            noDataState: Alerting
            execErrState: Alerting
            for: 10s
            annotations:
              summary: "CRITICAL SYSTEM DISASTER: dr-web-app deployment has 0 available replicas!"
            labels:
              severity: critical

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alert-notifiers
  namespace: monitoring
  labels:
    grafana_alert_notifiers: "1"
data:
  notifiers.yaml: |
    apiVersion: 1
    contactPoints:
      - orgId: 1
        name: Slack Channel
        receivers:
          - uid: slack_receiver
            type: slack
            settings:
              url: "{{ alert_webhook_url }}"
              sendResolved: true
              title: "🚨 [{{ '{{ .Status | toUpper }}' }}] {{ '{{ .CommonAnnotations.summary }}' }}"
    policies:
      - orgId: 1
        receiver: Slack Channel
        group_by: ['alertname', 'severity']
        group_wait: 5s
        group_interval: 10s
        repeat_interval: 1m