name: Manual Chaos & DR Simulation

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose failover or failback action'
        required: true
        default: 'failover'
        type: choice
        options:
          - failover
          - failback

jobs:
  inject_disaster:
    name: "Execute Chaos Injection"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Fetch Target VM IP from Terraform Cloud
        id: fetch_ip
        working-directory: terraform
        env:
          TF_VAR_target_vpc_id: ${{ vars.MY_VPC_ID }}
          TF_VAR_target_subnet_id: ${{ vars.MY_SUBNET_ID }}
        run: |
          terraform init -input=false
          echo "VM_IP=$(terraform output -raw vm_public_ip)" >> $GITHUB_ENV

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Build Ansible Environment
        working-directory: ansible
        run: |
          echo "${{ secrets.VM_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          echo "[target_vm]" > inventory.ini
          echo "${{ env.VM_IP }} ansible_user=ubuntu ansible_ssh_private_key_file=private_key.pem" >> inventory.ini

      - name: Fire Disaster Scenario
        timeout-minutes: 20
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          ALERT_WEBHOOK_URL: ${{ secrets.ALERT_WEBHOOK_URL }}
        working-directory: ansible
        run: |
          ansible-playbook -i inventory.ini chaos.yml -e "fail_stage=${{ github.event.inputs.action }}"